"""
Django settings for webdev project - CONFIGURACIÓN CON SENDGRID

Generated by 'django-admin startproject' using Django 3.1.5.
"""
from logging.handlers import TimedRotatingFileHandler
from pathlib import Path
import os
from dotenv import load_dotenv 
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    load_dotenv(dotenv_file)
else:
    load_dotenv()

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ['SECRET_KEY']

if not SECRET_KEY:
    raise Exception("No SECRET_KEY set in environment. Please check your .env file.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['weaponnotificationserver.onrender.com','0.0.0.0','127.0.0.1',]




# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'detection',
    'alertuploadREST',
    'django_filters',
    'rest_framework.authtoken',
    'django_extensions',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==========================================
# 🔐 SEGURIDAD DE SESIONES
# ==========================================
# Evita el "auto-login" tras reiniciar el servidor:
#  - La sesión termina al cerrar el navegador.
#  - Caduca por inactividad (expiración deslizante).
#  - Además, todas las sesiones se borran en el arranque en frío
#    (ver `flush_all_sessions` + hook `on_starting` de gunicorn_config.py).
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # cerrar el navegador termina la sesión
SESSION_COOKIE_AGE = 1800                # 30 min de inactividad
SESSION_SAVE_EVERY_REQUEST = True        # expiración deslizante (se renueva con actividad)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# Cookies solo por HTTPS en producción. Se activa con SECURE_COOKIES=true
# (p. ej. en Render); por defecto False para no romper el desarrollo local en http.
SESSION_COOKIE_SECURE = os.environ.get('SECURE_COOKIES', 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('SECURE_COOKIES', 'False').lower() == 'true'

ROOT_URLCONF = 'webdev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webdev.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': '5432',
        'OPTIONS': {
            'connect_timeout': 5,
            'sslmode': 'require',
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Logging
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS =[
    BASE_DIR / "static"
]
MEDIA_ROOT = 'static/images'

# ==========================================
# ✅ GMAIL SMTP EMAIL CONFIGURATION
# ==========================================
# Se usa Gmail vía SMTP con una "App Password" (contraseña de aplicación).
# Credenciales por variables de entorno (.env / Render):
#   EMAIL_HOST_USER      = tu-correo@gmail.com
#   EMAIL_HOST_PASSWORD  = app password de 16 caracteres (sin espacios)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# Se limpian espacios: Google muestra la app password en bloques de 4 (xxxx xxxx ...).
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').replace(' ', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@weapondetection.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_TIMEOUT = 30

# ==========================================
# ✅ BREVO API HTTP (envío real de correos)
# ==========================================
# Render bloquea el SMTP saliente, así que alertas y reset de contraseña se
# envían por la API HTTP de Brevo (puerto 443). La API key empieza con 'xkeysib-'.
# El remitente (DEFAULT_FROM_EMAIL) DEBE estar verificado en Brevo (Senders).
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
if not BREVO_API_KEY:
    print("\n[!] BREVO_API_KEY no configurado - los correos NO se enviaran.\n")

if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    import warnings
    warnings.warn(
        "⚠️ Gmail no configurado. Los emails no se enviarán. "
        "Agrega EMAIL_HOST_USER y EMAIL_HOST_PASSWORD a tu .env / Render.",
        RuntimeWarning
    )
    print("\n" + "="*60)
    print("[X] CONFIGURACION DE GMAIL INCOMPLETA")
    print("="*60)
    print("Necesitas agregar a tu .env / Render:")
    print("  EMAIL_HOST_USER=tu-correo@gmail.com")
    print("  EMAIL_HOST_PASSWORD=app-password-de-16-caracteres")
    print("="*60 + "\n")
else:
    print("\n" + "="*60)
    print("[OK] GMAIL SMTP CONFIGURADO")
    print("="*60)
    print(f"   From Email: {DEFAULT_FROM_EMAIL}")
    print(f"   SMTP Host: {EMAIL_HOST}:{EMAIL_PORT}")
    print("="*60 + "\n")

# Amazon S3 Configuration
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME = 'weapondetectionsystem'
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL=None

# Media files configuration
PUBLIC_MEDIA_LOCATION = 'media'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
DEFAULT_FILE_STORAGE = 'webdev.storage_backends.PublicMediaStorage'

# ==========================================
# 🔔 WEB PUSH (VAPID)
# ==========================================
# Claves del par VAPID para notificaciones Web Push (estándar abierto, sin FCM).
# Genera el par con:  python manage.py generate_vapid_keys
# y guarda los valores en variables de entorno (.env local / env vars en Render).
# NUNCA hardcodear estas claves en el repositorio.
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
# El claim "sub" del JWT VAPID: un mailto o una URL de contacto del responsable.
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'mailto:admin@weapondetection.com')