# Generated by Django 3.1.5 on 2024-09-04 05:16

import detection.models
from django.db import migrations, models
import django.db.models.deletion
import webdev.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=webdev.storage_backends.PublicMediaStorage(), upload_to=detection.models.scrambleUploadedFilename, verbose_name='Uploaded image')),
                ('alertReceiver', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
    ]
